import '../models/book.dart';

class SampleBooks {
  static List<Book> getSampleBooks() {
    return [
      Book(
        title: 'Flutter for Beginners',
        author: 'Thomas Kühne',
        isbn: '978-1449355738',
        category: 'Programming',
        course: 'CS101',
        status: 'Available',
        school: 'school-of-natural-and-applied-sciences',
        department: 'Department of Computer Science',
      ),
      Book(
        title: 'Dart Programming',
        author: 'Steve Grines',
        isbn: '978-1680505122',
        category: 'Programming',
        course: 'CS102',
        status: 'Available',
        school: 'school-of-natural-and-applied-sciences',
        department: 'Department of Computer Science',
      ),
      Book(
        title: 'Firebase Realtime Database',
        author: 'David East',
        isbn: '978-1491927275',
        category: 'Database',
        course: 'CS201',
        status: 'Available',
        school: 'school-of-natural-and-applied-sciences',
        department: 'Department of Computer Science',
      ),
      Book(
        title: 'Mobile Development Essentials',
        author: 'Mark Wickham',
        isbn: '978-1491945612',
        category: 'Mobile Development',
        course: 'CS150',
        status: 'Borrowed',
        school: 'school-of-natural-and-applied-sciences',
        department: 'Department of Engineering',
      ),
      Book(
        title: 'UI/UX Design Principles',
        author: 'Chris Nodder',
        isbn: '978-1491945606',
        category: 'Design',
        course: 'DESIGN101',
        status: 'Available',
        school: 'school-of-arts-communication-and-design',
        department: 'Department of Design',
      ),
      Book(
        title: 'Advanced Dart Patterns',
        author: 'Robert Martin',
        isbn: '978-0134494166',
        category: 'Programming',
        course: 'CS301',
        status: 'Available',
        school: 'school-of-natural-and-applied-sciences',
        department: 'Department of Computer Science',
      ),
      Book(
        title: 'Educational Psychology Handbook',
        author: 'Linda Darling-Hammond',
        isbn: '978-0470598718',
        category: 'Education',
        course: 'EDU101',
        status: 'Available',
        school: 'school-of-education',
        department: 'Department of Educational Studies',
      ),
      Book(
        title: 'Contemporary African History',
        author: 'Basil Davidson',
        isbn: '978-0851247731',
        category: 'History',
        course: 'HIST201',
        status: 'Available',
        school: 'school-of-humanities-and-social-sciences',
        department: 'Department of History',
      ),
      Book(
        title: 'Communication Theory Today',
        author: 'Judy Lont',
        isbn: '978-0742554429',
        category: 'Communication',
        course: 'COMM150',
        status: 'Available',
        school: 'school-of-arts-communication-and-design',
        department: 'Department of Communication',
      ),
      Book(
        title: 'Environmental Science Principles',
        author: 'William Cunningham',
        isbn: '978-0073532547',
        category: 'Environmental Studies',
        course: 'ENV101',
        status: 'Available',
        school: 'school-of-natural-and-applied-sciences',
        department: 'Department of Environmental Studies',
      ),
    ];
  }
}
